### ISSUE TITLE
Does not work when Starkvind Air Purifier is present

### ISSUE THREAD

**Issue by julijane** [lpgera/tradfri-web-ui#2]
Title says it all. I have a Starkvind Air Purifier in my Tradfri Setup and this leads to an error because the enum does not know it (accessorytype is 10 for the air purifier). I already tried updating node-tradfri-client and adding it to the code of tradfri-web-ui, but it seems to be not that easy as I now have another error.

**Comment by lpgera** [comment]
Hi @julijane, thanks for the bug report!

I'm not sure how exactly you tried to add the new enum value, so I created a new PR (#3) which supposedly fixes the error which you encountered in the GraphQL server because of the schema mismatch.

As I don't own such an air purifier product, I can't currently test whether the PR really fixes all errors, so would you be able to verify it for me before I merge it please? If you encounter any issues, let me know by commenting on the PR.

Also, please keep in mind that the linked PR does not add any air purifier specific functionalities, which means that you won't be able to control your device via the web UI. The same is true for window blinds too. I'm planning to add further functionalities in the future, but PRs are welcome in the meantime! 😉
